/***************************************************************************
*     Copyright (C), 2014, Triductor Technology, Inc. All rights reserved.
*
*     FileName    : defs.h
*     Author      : Daniel Ni
*     Version     : V1.0       
*     Date        : 2014/06/16 
*     Description : header file of typdefs
*     Other       :
*     History     :        
***************************************************************************/
#ifndef __DEFS_INC__
#define __DEFS_INC__

typedef signed char s8;
typedef unsigned char u8;

typedef signed short s16;
typedef unsigned short u16;

typedef signed int s32;
typedef unsigned int u32;

typedef signed long long s64;
typedef unsigned long long u64;

#endif
